import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {handleInquiry,validateInquiry,retryNotifications} from '../server/inquiries.mjs';
function database(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../migrations/0001_inquiries.sql',import.meta.url),'utf8'));return {db,prepare(sql){return {bind(...args){return {async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){db.prepare(sql).run(...args);return {success:true};}};}};}};}
const payload=()=>({schemaVersion:1,submissionId:crypto.randomUUID(),inquiryType:'sample',company:'Test Company',contactName:'Test Person',email:'test@example.com',productCategory:'wall',modelIds:['TB-W-001'],message:'Test inquiry only',privacyAccepted:true,sourcePath:'/wholesale/samples/',utm:{},turnstileToken:'mock-token'});
const request=(body,origin='https://tilebase.jp')=>new Request('https://tilebase.jp/api/inquiries',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin,'cf-connecting-ip':'192.0.2.1'},body:JSON.stringify(body)});
const env=()=>({DB:database(),SITE_STAGE:'production',SITE_URL:'https://tilebase.jp',TURNSTILE_SECRET_KEY:'mock',RATE_LIMIT_SALT:'test-salt',RESEND_API_KEY:'mock',FROM_EMAIL:'test@example.com',INQUIRY_EMAIL:'test@example.com',RETRY_TOKEN:'test-token'});
const fetchOk=async url=>new Response(JSON.stringify(String(url).includes('siteverify')?{success:true,hostname:'tilebase.jp',action:'inquiry'}:{id:'mock-email'}),{status:200});
test('validates product IDs and strips unknown data and tokens',()=>{const body=payload();const result=validateInquiry({...body,extra:'ignored'});assert.deepEqual(result.modelIds,['TB-W-001']);assert.equal(result.turnstileToken,undefined);assert.equal(result.extra,undefined);assert.throws(()=>validateInquiry({...body,modelIds:['UNKNOWN']}));assert.throws(()=>validateInquiry({...body,email:'bad\nheader@example.com'}));assert.throws(()=>validateInquiry({...body,privacyAccepted:false}));});
test('preview and incomplete configuration never accept data',async()=>{assert.equal((await handleInquiry(request(payload()),{SITE_STAGE:'preview'})).status,503);assert.equal((await handleInquiry(request(payload()),{SITE_STAGE:'production'})).status,503);});
test('origin, JSON format and honeypot are enforced',async()=>{const e=env();assert.equal((await handleInquiry(request(payload(),'https://other.example'),e)).status,403);assert.equal((await handleInquiry(request({...payload(),websiteTrap:'spam'}),e)).status,400);assert.equal((await handleInquiry(new Request('https://tilebase.jp/api/inquiries',{method:'POST',headers:{Origin:'https://tilebase.jp','Content-Type':'application/json'},body:'bad-json'}),e)).status,400);e.DB.db.close();});
test('oversized bodies and malformed IDs do not reach storage',async()=>{const e=env();assert.equal((await handleInquiry(request({...payload(),message:'x'.repeat(21000)}),e)).status,413);assert.equal((await handleInquiry(request({...payload(),submissionId:'123'}),e)).status,400);assert.equal(e.DB.db.prepare('SELECT COUNT(*) AS n FROM inquiries').get().n,0);e.DB.db.close();});
test('turnstile success must match hostname and action',async()=>{const e=env();const res=await handleInquiry(request(payload()),e,{}, {fetch:async()=>new Response(JSON.stringify({success:true,hostname:'other.example',action:'inquiry'}))});assert.equal(res.status,400);assert.equal(e.DB.db.prepare('SELECT COUNT(*) AS n FROM inquiries').get().n,0);e.DB.db.close();});
test('successful submission is durable and repeated requests are deduplicated',async()=>{const e=env(),body=payload();const a=await handleInquiry(request(body),e,{}, {fetch:fetchOk});assert.equal(a.status,201);const first=await a.json();const b=await handleInquiry(request(body),e,{}, {fetch:fetchOk});assert.equal(b.status,200);const second=await b.json();assert.equal(first.inquiryId,second.inquiryId);assert.equal(second.deduplicated,true);const row=e.DB.db.prepare('SELECT * FROM inquiries').get();assert.equal(row.notification_status,'sent');assert.equal(row.status,'new');assert.equal(JSON.parse(row.payload).turnstileToken,undefined);assert.equal(e.DB.db.prepare('SELECT COUNT(*) AS n FROM inquiries').get().n,1);e.DB.db.close();});
test('failed email preserves saved inquiry, retry succeeds, and retry route requires a secret',async()=>{const e=env();const result=await handleInquiry(request(payload()),e,{}, {fetch:async url=>String(url).includes('siteverify')?fetchOk(url):new Response('{}',{status:500})});assert.equal(result.status,201);const id=(await result.json()).inquiryId;assert.equal(e.DB.db.prepare('SELECT notification_status FROM inquiries').get().notification_status,'failed');assert.equal((await retryNotifications(new Request('https://tilebase.jp/api/retry',{method:'POST'}),e,fetchOk)).status,401);e.DB.db.prepare('UPDATE inquiries SET next_retry_at = ? WHERE inquiry_id = ?').run('2000-01-01T00:00:00.000Z',id);const retry=await retryNotifications(new Request('https://tilebase.jp/api/retry',{method:'POST',headers:{Authorization:'Bearer test-token'}}),e,fetchOk);assert.equal(retry.status,200);assert.equal((await retry.json()).sent,1);assert.equal(e.DB.db.prepare('SELECT notification_status FROM inquiries').get().notification_status,'sent');e.DB.db.close();});
test('rate limit enforces 10 attempts per 10 minutes without storing raw IP',async()=>{const e=env();for(let i=0;i<10;i++)assert.equal((await handleInquiry(request(payload()),e,{}, {fetch:fetchOk})).status,201);const response=await handleInquiry(request(payload()),e,{}, {fetch:fetchOk});assert.equal(response.status,429);const row=e.DB.db.prepare('SELECT * FROM inquiry_limits').get();assert.match(row.client_hash,/^[0-9a-f]{64}$/);assert.equal(row.attempts,11);e.DB.db.close();});
test('storage failure never returns a success acknowledgement',async()=>{const e=env();e.DB={prepare(){throw new Error('Database unavailable');}};assert.equal((await handleInquiry(request(payload()),e,{}, {fetch:fetchOk})).status,503);});
