import { existsSync, readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { loadEnv } from 'vite';
const readJson=path=>JSON.parse(readFileSync(path,'utf8').replace(/^\uFEFF/,''));
const config=readJson('wrangler.jsonc');
const facts=readJson('launch-readiness.json');
const env={...loadEnv('production',process.cwd(),''),...process.env};
const checks=[];
const add=(name,passed,note)=>checks.push({name,passed:Boolean(passed),note});
for(const [name,confirmed] of Object.entries(facts))add(name,confirmed===true,'Requires actual verification; this script never changes approval flags.');
add('realDatabaseBinding',config.d1_databases?.some(db=>db.binding==='DB'&&/^[0-9a-f-]{36}$/i.test(db.database_id||'')&&!/^0{8}-0{4}-0{4}-0{4}-0{12}$/.test(db.database_id)),'Configured binding only; service verification is separately required.');
add('matchingProductionStages',env.PUBLIC_SITE_STAGE==='production'&&config.vars?.SITE_STAGE==='production','Both browser build and runtime must explicitly be production.');
for(const name of ['PUBLIC_CONTACT_EMAIL','PUBLIC_TURNSTILE_SITE_KEY'])add(name,Boolean(env[name]),'Checks presence in local build environment, never prints value.');
add('matchingCanonicalOrigin',Boolean(env.SITE_URL?.startsWith('https://')&&env.SITE_URL===config.vars?.SITE_URL),'Build and runtime origins must match; ownership/DNS/HTTPS still require external verification.');
if(existsSync('dist/robots.txt'))add('crawlAllowed',!/^Disallow:\s*\/\s*$/m.test(readFileSync('dist/robots.txt','utf8')),'Preview intentionally disallows crawling.');else add('crawlAllowed',false,'Build output missing.');
if(existsSync('dist/sitemap.xml'))add('nonemptySitemap',/<loc>https:\/\//.test(readFileSync('dist/sitemap.xml','utf8')),'Preview intentionally emits an empty sitemap.');else add('nonemptySitemap',false,'Build output missing.');
const report={checkedAt:new Date().toISOString(),configurationReady:checks.every(c=>c.passed),checks,notProvenByThisScript:['Public domain ownership, DNS and HTTPS','Working mailbox and sender verification','Deployed secrets and Turnstile verification','Actual database save and email receipt','Search Console ownership and indexing','Organic search clicks and qualified inquiries']};
mkdirSync('qa',{recursive:true});writeFileSync('qa/launch-check.json',JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
if(!report.configurationReady)process.exitCode=1;
